---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  guest:
    default_front_matter_template: guest
  episode:
    default_front_matter_template: episode
  about:
    default_front_matter_template: about
version: 0.30.2
